version: 2

sources:
  - name: jaffle_shop
    description: Raw data loaded from seeds (DuckDB)
    schema: main_raw

    tables:
      - name: customers
        description: Raw customers seed
        columns:
          - name: id
            description: Customer ID
          - name: first_name
            description: Customer first name
          - name: last_name
            description: Customer last name

      - name: orders
        description: Raw orders seed
        columns:
          - name: id
            description: Order ID
          - name: user_id
            description: User ID
          - name: order_date
            description: Order date
          - name: status
            description: Order status

      - name: stripe_payments
        description: Stripe payment data
        columns:
          - name: id
            description: Payment ID
          - name: order_id
            description: Order ID
          - name: payment_method
            description: Payment method
          - name: amount
            description: Payment amount
          - name: created
            description: Payment creation date


